### ISSUE TITLE
Microservice - Authentication Service

### ISSUE THREAD

**Issue by EdwardLim1994** [EdwardLim1994/CodeLearn#2]
## Tasks

- [ ] Connect to PocketBase
- [ ] authenticate user using email & social account
- [ ] login & logout
- [ ] Verify request origin
