### ISSUE TITLE
Microservice - Course Service

### ISSUE THREAD

**Issue by EdwardLim1994** [EdwardLim1994/CodeLearn#4]
## Tasks

- [ ] Connect to SurrealDB
- [ ] Connect to RabbitMQ
- [ ] Create migration script
- [ ] Create course as well as quizzes
- [ ] Update course
- [ ] Delete course
- [ ] Upload video to Vimeo
- [ ] Upload image to Cloudinary
- [ ] Produce topic to RabbitMQ
